### ISSUE TITLE
Element disappearing

### ISSUE THREAD

**Issue by anujpuri72** [MAARK-2-0/Wix-clone#10]
@anvaymishra1 @RohithChittibommala @Mayankbazari  PTAl
it's just a one line of code
do it and send PR asap

**Comment by pAditya198** [comment]
@anujpuri72 can you explain what's happening?

**Comment by anvaymishra1** [comment]
I think he's talking about the elements getting disappeared after placing them beyond a certain position on the canvas

**Comment by pAditya198** [comment]
Okay.
Any one working on it?

**Comment by anvaymishra1** [comment]
I am trying but am unable to find a solution.

**Comment by Mayankbazari** [comment]
I also face same problems. Is it because of margin and padding?

**Comment by pAditya198** [comment]
Nope man 
It's quite a simple bug that's wahy I had asked three of them to solve that issue

**Comment by anvaymishra1** [comment]
maybe it has got to do something with the canvas because when we drag it out of the screen it disappears

**Comment by pAditya198** [comment]
Is this issue fixed please do it ASAP

**Comment by anvaymishra1** [comment]
> Is this issue fixed please do it ASAP

I guess it is . Check it once then we can close this
