### ISSUE TITLE
Working Demo

### ISSUE THREAD

**Issue by skadewdl3** [MAARK-2-0/Wix-clone#14]
Hey guys, you have got a great app .Where can I find a working demo of this app, I feel like I can learn a lot from it. Cheers 👍

**Comment by pAditya198** [comment]
We don't have a working demo yet we'll work on it ASAP. If you wanna set up the environment just go through the Readme.md file

**Comment by skadewdl3** [comment]
Alright, thanks a lot.

**Comment by pAditya198** [comment]
If you face any problem contact me or anyone on the team.

**Comment by skadewdl3** [comment]
Sure. Thanks a lot. If possible, can I contribute to this project ?

I've made somthing similar. It's not exactly like Wix. It's at: https://mulyankan.netlify.app

**Comment by anujpuri72** [comment]
Sure why not
